import localFont, { Geist, Geist_Mono } from "next/font/local";
import { ToastContainer, toast } from 'react-toastify';
import "./globals.css";
import NextSessionProviders from "./session-provider";
import Navbar from "./components/navbar";
import Footer from "./components/footer";



const caterina = localFont({
  src: '../assets/fonts/Caterina.woff2',
  variable: '--font-caterina',
})

const arefRuqaa = localFont({
  src: '../assets/fonts/ArefRuqaa-Regular.woff2',
  variable: '--font-aref-ruqaa',
})

const bdMegalona = localFont({ 
  src: '../assets/fonts/BDMegalona.woff2',
  variable: '--font-bd-megalona',
})

export const metadata = {
  title: "Mimz Interiors",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${caterina.variable} ${arefRuqaa.variable} ${bdMegalona.variable}`} >
      <body
        className={` ${arefRuqaa.className} } antialiased min-h-screen flex flex-col`}
      >
        <NextSessionProviders>
          <Navbar />
          <main className="flex-1">{children}</main>
          <Footer />
        </NextSessionProviders>
         <ToastContainer />
      </body>
    </html>
  );
}
