import localFont from "next/font/local";
import { ToastContainer, toast } from 'react-toastify';
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import NextSessionProviders from "./session-provider";
import SiteShell from "./components/site-shell";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth";



const caterina = localFont({
  src: '../assets/fonts/Caterina.woff2',
  variable: '--font-caterina',
})

const arefRuqaa = localFont({
  src: '../assets/fonts/ArefRuqaa-Regular.woff2',
  variable: '--font-aref-ruqaa',
})

const bdMegalona = localFont({ 
  src: '../assets/fonts/BDMegalona.woff2',
  variable: '--font-bd-megalona',
})

export const metadata = {
  title: "Mimz Interiors",
  description: "Generated by create next app",
};


export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en" className={`${caterina.variable} ${arefRuqaa.variable} ${bdMegalona.variable}`} >
      <body
        className={`${arefRuqaa.className} antialiased`}
      >
        <NextTopLoader color="#C9A96E" showSpinner={false} />
        <NextSessionProviders session={session}>
          <SiteShell>{children}</SiteShell>
        </NextSessionProviders>
         <ToastContainer />
      </body>
    </html>
  );
}
