import { Geist, Geist_Mono } from "next/font/google";
import { ToastContainer, toast } from 'react-toastify';
import "./globals.css";
import NextSessionProviders from "./session-provider";
import Navbar from "./components/navbar";
import Footer from "./components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Mimz Interiors",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <NextSessionProviders>
          <Navbar />
          <main className="flex-1">{children}</main>
          <Footer />
        </NextSessionProviders>
         <ToastContainer />
      </body>
    </html>
  );
}
